#![deny(clippy::dbg_macro)]
#![deny(unused_crate_dependencies)]

use proc_macro2::{Span, TokenStream};
use syn::spanned::Spanned;

mod types;

pub(crate) use self::types::*;

fn fatality_inner(input: proc_macro2::TokenStream) -> syn::Result<proc_macro2::TokenStream> {
    let bail_if_has_generics = |generics: &syn::Generics, span: Span| -> syn::Result<()> {
        if !generics.params.is_empty() {
            return Err(syn::Error::new(
                span,
                "Generics  `enum`-types are currently supported",
            ));
        }
        Ok(())
    };
    match syn::parse2::<syn::Item>(input.clone())? {
        syn::Item::Enum(item) => {
            bail_if_has_generics(&item.generics, item.span())?;
            fatality_enum_gen(item)
        }
        syn::Item::Struct(item) => {
            bail_if_has_generics(&item.generics, item.span())?;
            fatality_struct_gen(item)
        }
        other => Err(syn::Error::new(
            other.span(),
            "Only `enum` and `struct` types are supported",
        )),
    }
}

#[proc_macro_derive(Fatality, attributes(fatal))]
pub fn derive_fatality(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = TokenStream::from(input);
    let output: TokenStream = {
        let ts = fatality_inner(input.clone()).unwrap_or_else(|e| -> proc_macro2::TokenStream {
            let mut ts = proc_macro2::TokenStream::new();
            ts.extend(input);
            ts.extend(e.to_compile_error());
            ts
        });

        expander::Expander::new("fatality")
            .add_comment("Generated by `#[derive(::fatality::Fatality)]`".to_owned())
            // .fmt(expander::Edition::_2021)
            .dry(!cfg!(feature = "expand"))
            .write_to_out_dir(ts)
            .unwrap()
    };
    proc_macro::TokenStream::from(output)
}

fn split_inner(input: proc_macro2::TokenStream) -> syn::Result<proc_macro2::TokenStream> {
    let bail_if_has_generics = |generics: &syn::Generics, span: Span| -> syn::Result<()> {
        if !generics.params.is_empty() {
            return Err(syn::Error::new(
                span,
                "Generics  `enum`-types are currently supported",
            ));
        }
        Ok(())
    };
    match syn::parse2::<syn::Item>(input.clone())? {
        syn::Item::Enum(item) => {
            bail_if_has_generics(&item.generics, item.span())?;
            split_enum_gen(item)
        }
        syn::Item::Struct(item) => {
            bail_if_has_generics(&item.generics, item.span())?;
            split_struct_gen(input.span(), item)
        }
        other => Err(syn::Error::new(
            other.span(),
            "Only `enum` and `struct` types are supported",
        )),
    }
}

#[proc_macro_derive(Split)]
pub fn derive_split(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = TokenStream::from(input);
    let output: TokenStream = {
        let ts = split_inner(input.clone()).unwrap_or_else(|e| -> proc_macro2::TokenStream {
            let mut ts = proc_macro2::TokenStream::new();
            ts.extend(input);
            ts.extend(e.to_compile_error());
            ts
        });

        expander::Expander::new("fatality")
            .add_comment("Generated by `#[derive(::fatality::Split)]`".to_owned())
            // .fmt(expander::Edition::_2021)
            .dry(!cfg!(feature = "expand"))
            .write_to_out_dir(ts)
            .unwrap()
    };
    proc_macro::TokenStream::from(output)
}

#[cfg(test)]
mod tests;
